

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "Markel.GlobalRe.Service.Underwriting.Data\app.config"
//     Connection String Name: "ERMSDbContext"
//     Connection String:      "Server=ERMSDB_DEV;Database=GRS_ERMS;Trusted_Connection=True;Connect Timeout=5000;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Enterprise Edition: Core-based Licensing (64-bit)
// Database Engine Edition: Enterprise

// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Data.Entity.Infrastructure;
using System.Xml.Serialization;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;

namespace Markel.GlobalRe.Service.Underwriting.Data.Models
{

    // ************************************************************************
    // POCO classes

    // cfgRole
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class CfgRole
    {
        public int RolePk { get; set; } // RolePK (Primary key)
        public string Name { get; set; } // Name
        public int? ParentRoleFk { get; set; } // ParentRoleFK
        public Guid? ActiveDirectorySyncGuid { get; set; } // ActiveDirectorySyncGUID
        public bool Active { get; set; } // Active
        public string SourceOfRole { get; set; } // SourceOfRole

        // Reverse navigation
        public virtual ICollection<CfgRole> CfgRoles { get; set; } // cfgRole.FK_Role_Role
        public virtual ICollection<CfgRolePerson> CfgRolePersons { get; set; } // cfgRolePerson.FK_RolePerson_Role

        // Foreign keys
        public virtual CfgRole CfgRole_ParentRoleFk { get; set; } // FK_Role_Role
        
        public CfgRole()
        {
            Active = true;
            SourceOfRole = "N'Local'";
            CfgRoles = new List<CfgRole>();
            CfgRolePersons = new List<CfgRolePerson>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // cfgRolePerson
    public partial class CfgRolePerson
    {
        public int RolePersonPk { get; set; } // RolePersonPK (Primary key)
        public int RoleFk { get; set; } // RoleFK
        public int PersonNameFk { get; set; } // PersonNameFK

        // Foreign keys
        public virtual CfgRole CfgRole { get; set; } // FK_RolePerson_Role
        
        public CfgRolePerson()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tbl_userviews
    public partial class grs_TblUserview
    {
        public int ViewId { get; set; } // view_id (Primary key)
        public int Userid { get; set; } // userid
        public string Screenname { get; set; } // screenname
        public string Viewname { get; set; } // viewname
        public bool @Default { get; set; } // default
        public string Layout { get; set; } // layout
        public bool Customview { get; set; } // customview
        public int Sortorder { get; set; } // sortorder
        public DateTime? UserViewCreationDate { get; set; } // UserViewCreationDate

        // Foreign keys
        public virtual TbUser TbUser { get; set; } // FK_tb_user_tbl_userviews
        
        public grs_TblUserview()
        {
            @Default = false;
            Customview = true;
            Sortorder = 0;
            UserViewCreationDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_CatalogItemsExt
    public partial class grs_VCatalogItemsExt
    {
        public int Catid { get; set; } // catid
        public int Catorder { get; set; } // catorder
        public int Code { get; set; } // code
        public string Charcode { get; set; } // charcode
        public string Name { get; set; } // name
        public bool Active { get; set; } // active
        public int? Intdata1 { get; set; } // intdata1
        public string Strdata1 { get; set; } // strdata1
        public double? FloatData1 { get; set; } // FloatData1
        public int? AssumedFlag { get; set; } // AssumedFlag
        public int? AssumedSortOder { get; set; } // AssumedSortOder
        public string AssumedName { get; set; } // AssumedName
        public int? CededFlag { get; set; } // CededFlag
        public int? CededSortOrder { get; set; } // CededSortOrder
        public string CededName { get; set; } // CededName
        
        public grs_VCatalogItemsExt()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_DMSFileType
    public partial class grs_VDmsFileType
    {
        public int DmsSystem { get; set; } // DmsSystem
        public int UnderwritingTeamFk { get; set; } // UnderwritingTeamFK
        public int DocType { get; set; } // DocType
        public byte IsBound { get; set; } // IsBound
        public string FileType { get; set; } // FileType
        public string Folder { get; set; } // Folder
        public string DocumentLog { get; set; } // DocumentLog
        public byte IsOutward { get; set; } // IsOutward
        public int Dealnum { get; set; } // dealnum
        public int? Producer { get; set; } // producer
        
        public grs_VDmsFileType()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_ExposureTreeExt
    public partial class grs_VExposureTreeExt
    {
        public string SubdivisionName { get; set; } // SubdivisionName
        public int? SubdivisionCode { get; set; } // SubdivisionCode
        public int ProductLineCode { get; set; } // ProductLineCode
        public string ProductLineName { get; set; } // ProductLineName
        public int ExposureGroupCode { get; set; } // ExposureGroupCode
        public string ExposureGroupName { get; set; } // ExposureGroupName
        public int ExposureTypeCode { get; set; } // ExposureTypeCode
        public string ExposureTypeName { get; set; } // ExposureTypeName
        
        public grs_VExposureTreeExt()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRDealStatus
    public partial class grs_VGrDealStatu
    {
        public int WorkflowId { get; set; } // WorkflowID
        public string WorkflowName { get; set; } // WorkflowName
        public int GroupId { get; set; } // GroupID
        public string GroupName { get; set; } // GroupName
        public int GroupSortOrder { get; set; } // GroupSortOrder
        public int StatusCode { get; set; } // StatusCode
        public string StatusName { get; set; } // StatusName
        public int StatusSortOrder { get; set; } // StatusSortOrder
        
        public grs_VGrDealStatu()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSBrokers
    public partial class grs_VGrsBroker
    {
        public int? Brokercontactid { get; set; } // brokercontactid
        public string Brokercontact { get; set; } // brokercontact
        public string Firstname { get; set; } // firstname
        public string Lastname { get; set; } // lastname
        public string Email { get; set; } // email
        public string Phone { get; set; } // phone
        public string Fax { get; set; } // fax
        public string Website { get; set; } // website
        public string Mobilephone { get; set; } // mobilephone
        public string Otherphone { get; set; } // otherphone
        public string Otheremail { get; set; } // otheremail
        public string Homephone { get; set; } // homephone
        public string Homefax { get; set; } // homefax
        public string Homeemail { get; set; } // homeemail
        public string Officeextension { get; set; } // officeextension
        public string Speeddial { get; set; } // speeddial
        public int? Brokerid { get; set; } // brokerid
        public string Broker { get; set; } // broker
        public int? Parentgrouptypeid { get; set; } // parentgrouptypeid
        public string Parentgrouptype { get; set; } // parentgrouptype
        public int? Brokergroupid { get; set; } // brokergroupid
        public string Brokergroupname { get; set; } // brokergroupname
        public int Locationid { get; set; } // locationid
        public string AmsCode { get; set; } // AMSCode
        public string Locationname { get; set; } // locationname
        public string Locationaddress { get; set; } // locationaddress
        public string Locationcity { get; set; } // locationcity
        public string Locationstate { get; set; } // locationstate
        public string Locationpostcode { get; set; } // locationpostcode
        public string Country { get; set; } // country
        public string Parentcompanyname { get; set; } // parentcompanyname
        public string Brokercategories { get; set; } // brokercategories
        public string Brokercategoryid { get; set; } // brokercategoryid
        
        public grs_VGrsBroker()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSCedants
    public partial class grs_VGrsCedant
    {
        public int? Cedantid { get; set; } // cedantid
        public string Cedant { get; set; } // cedant
        public int? Parentgrouptypeid { get; set; } // parentgrouptypeid
        public string Parentgrouptype { get; set; } // parentgrouptype
        public int? Cedantgroupid { get; set; } // cedantgroupid
        public string Cedantgroupname { get; set; } // cedantgroupname
        public int Locationid { get; set; } // locationid
        public string Locationname { get; set; } // locationname
        public string Locationaddress { get; set; } // locationaddress
        public string Locationcity { get; set; } // locationcity
        public string Locationstate { get; set; } // locationstate
        public string Locationpostcode { get; set; } // locationpostcode
        public string Country { get; set; } // country
        public string Parentcompanyname { get; set; } // parentcompanyname
        public string Cedantcategories { get; set; } // cedantcategories
        public string Cedantcategoryid { get; set; } // cedantcategoryid
        
        public grs_VGrsCedant()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSChecklistsByDeal
    public partial class grs_VGrsChecklistsByDeal
    {
        public int Dealnum { get; set; } // dealnum
        public int Entitynum { get; set; } // entitynum
        public string CategoryCharCode { get; set; } // CategoryCharCode
        public int? Category { get; set; } // Category
        public string CategoryShortName { get; set; } // CategoryShortName
        public string CategoryName { get; set; } // CategoryName
        public int? Catorder { get; set; } // catorder
        public int Chklistnum { get; set; } // chklistnum
        public string ChecklistName { get; set; } // ChecklistName
        public int? Sortorder { get; set; } // sortorder
        public bool? Readonly { get; set; } // Readonly
        public bool? Checked { get; set; } // Checked
        public int? PersonId { get; set; } // PersonId
        public string PersonName { get; set; } // PersonName
        public string FirstName { get; set; } // FirstName
        public string LastName { get; set; } // LastName
        public string MiddleName { get; set; } // MiddleName
        public DateTime? CheckedDateTime { get; set; } // CheckedDateTime
        public string Note { get; set; } // Note
        
        public grs_VGrsChecklistsByDeal()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSContractTypes
    public partial class grs_VGrsContractType
    {
        public long? RowId { get; set; } // RowID
        public int Code { get; set; } // code
        public int Catorder { get; set; } // catorder
        public string InsuranceName { get; set; } // InsuranceName
        public bool Active { get; set; } // active
        public string AssumedName { get; set; } // AssumedName
        public int? AssumedFlag { get; set; } // AssumedFlag
        public string CededName { get; set; } // CededName
        public int? CededFlag { get; set; } // CededFlag
        public int? Exposuretype { get; set; } // exposuretype
        public string Exposurename { get; set; } // exposurename
        
        public grs_VGrsContractType()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSDeals
    public partial class grs_VGrsDeal
    {
        public int Dealnum { get; set; } // dealnum
        public string Dealname { get; set; } // dealname
        public int? Contractnum { get; set; } // contractnum
        public DateTime? Inceptdate { get; set; } // inceptdate
        public DateTime? Expirydate { get; set; } // expirydate
        public bool? ExpiryEod { get; set; } // Expiry_EOD
        public DateTime? Targetdt { get; set; } // targetdt
        public int? ModelPriority { get; set; } // ModelPriority
        public DateTime? Submissiondate { get; set; } // submissiondate
        public int? Status { get; set; } // status
        public int? Outward { get; set; } // outward
        public string StatusName { get; set; } // status_name
        public int DealpipelineComplete { get; set; } // DealpipelineComplete
        public int InForce { get; set; } // InForce
        public int Renewable { get; set; } // Renewable
        public int? Uw1 { get; set; } // uw1
        public string Uw1Name { get; set; } // uw1_name
        public int? Uw2 { get; set; } // uw2
        public string Uw2Name { get; set; } // uw2_name
        public int? Ta { get; set; } // TA
        public string TaName { get; set; } // TA_Name
        public int? Modeller { get; set; } // Modeller
        public string ModellerName { get; set; } // modeller_name
        public int? Act1 { get; set; } // act1
        public string Act1Name { get; set; } // act1_name
        public int? Broker { get; set; } // broker
        public string BrokerName { get; set; } // broker_name
        public int? BrokerLocation { get; set; } // broker_location
        public string BrokerLocationname { get; set; } // broker_locationname
        public int? BrokerContact { get; set; } // broker_contact
        public string BrokerContactName { get; set; } // broker_contact_name
        public int? BrokerCompanygroupId { get; set; } // broker_companygroupId
        public string BrokerCompanygroup { get; set; } // broker_companygroup
        public string Division { get; set; } // division
        public int? Paper { get; set; } // paper
        public string PaperName { get; set; } // paper_name
        public int? Team { get; set; } // team
        public string TeamName { get; set; } // team_name
        public int? Exposuretype { get; set; } // exposuretype
        public bool? Continuous { get; set; } // continuous
        public int? Cedant { get; set; } // Cedant
        public string CedantName { get; set; } // cedant_name
        public int? CedentLocation { get; set; } // cedent_location
        public string CedentLocationname { get; set; } // cedent_locationname
        public int? CedentCompanygroupId { get; set; } // cedent_companygroupId
        public string CedentCompanygroup { get; set; } // cedent_companygroup
        public int? Renewal { get; set; } // renewal
        public string RenewalName { get; set; } // renewal_name
        public int? Dealtype { get; set; } // dealtype
        public string DealtypeName { get; set; } // dealtype_name
        public int? Coveragetype { get; set; } // coveragetype
        public string CoveragetypeName { get; set; } // coveragetype_name
        public int? Policybasis { get; set; } // policybasis
        public string PolicybasisName { get; set; } // policybasis_name
        public int? Currency { get; set; } // currency
        public string CurrencyName { get; set; } // currency_name
        public int? Domicile { get; set; } // domicile
        public string DomicileName { get; set; } // domicile_name
        public int? Region { get; set; } // region
        public string RegionName { get; set; } // region_name
        public string ChkPreBindProc { get; set; } // ChkPreBindProc
        public string ChkModeling { get; set; } // ChkModeling
        public string ChkUwCompliance { get; set; } // ChkUWCompliance
        
        public grs_VGrsDeal()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSDealCoverages
    public partial class grs_VGrsDealCoverage
    {
        public int Dealnum { get; set; } // dealnum
        public int CoverId { get; set; } // cover_id
        public string CoverName { get; set; } // cover_name
        
        public grs_VGrsDealCoverage()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSDealsByStatus
    public partial class grs_VGrsDealsByStatu
    {
        public int Dealnum { get; set; } // dealnum
        public string Dealname { get; set; } // dealname
        public int? Contractnum { get; set; } // contractnum
        public DateTime? Inceptdate { get; set; } // inceptdate
        public DateTime? Expirydate { get; set; } // expirydate
        public bool? ExpiryEod { get; set; } // Expiry_EOD
        public DateTime? Targetdt { get; set; } // targetdt
        public int? ModelPriority { get; set; } // ModelPriority
        public DateTime? Submissiondate { get; set; } // submissiondate
        public int? Status { get; set; } // status
        public string StatusName1 { get; set; } // status_name
        public int StatusCode { get; set; } // StatusCode
        public string StatusName { get; set; } // StatusName
        public int DealPipelineComplete { get; set; } // DealPipelineComplete
        public int InForce { get; set; } // InForce
        public int Renewable { get; set; } // Renewable
        public int? Uw1 { get; set; } // uw1
        public string Uw1Name { get; set; } // uw1_name
        public int? Uw2 { get; set; } // uw2
        public string Uw2Name { get; set; } // uw2_name
        public int? Ta { get; set; } // TA
        public string TaName { get; set; } // TA_Name
        public int? Modeller { get; set; } // Modeller
        public string ModellerName { get; set; } // modeller_name
        public int? Act1 { get; set; } // act1
        public string Act1Name { get; set; } // act1_name
        public int? Broker { get; set; } // broker
        public string BrokerName { get; set; } // broker_name
        public int? BrokerLocation { get; set; } // broker_location
        public string BrokerLocationname { get; set; } // broker_locationname
        public int? BrokerContact { get; set; } // broker_contact
        public string BrokerContactName { get; set; } // broker_contact_name
        public int? BrokerCompanygroupId { get; set; } // broker_companygroupId
        public string BrokerCompanygroup { get; set; } // broker_companygroup
        public string Division { get; set; } // division
        public int? Paper { get; set; } // paper
        public string PaperName { get; set; } // paper_name
        public int? Team { get; set; } // team
        public string TeamName { get; set; } // team_name
        public int? Exposuretype { get; set; } // exposuretype
        public int StatusGroup { get; set; } // StatusGroup
        public string StatusGroupName { get; set; } // StatusGroupName
        public int StatusGroupSortOrder { get; set; } // StatusGroupSortOrder
        public int StatusSortOrder { get; set; } // StatusSortOrder
        public bool? Continuous { get; set; } // continuous
        public int? Cedant { get; set; } // Cedant
        public string CedantName { get; set; } // cedant_name
        public int? CedentLocation { get; set; } // cedent_location
        public string CedentLocationname { get; set; } // cedent_locationname
        public int? CedentCompanygroupId { get; set; } // cedent_companygroupId
        public string CedentCompanygroup { get; set; } // cedent_companygroup
        public int? Renewal { get; set; } // renewal
        public string RenewalName { get; set; } // renewal_name
        public int? Dealtype { get; set; } // dealtype
        public string DealtypeName { get; set; } // dealtype_name
        public int? Coveragetype { get; set; } // coveragetype
        public string CoveragetypeName { get; set; } // coveragetype_name
        public int? Policybasis { get; set; } // policybasis
        public string PolicybasisName { get; set; } // policybasis_name
        public int? Currency { get; set; } // currency
        public string CurrencyName { get; set; } // currency_name
        public int? Domicile { get; set; } // domicile
        public string DomicileName { get; set; } // domicile_name
        public int? Region { get; set; } // region
        public string RegionName { get; set; } // region_name
        public string ChkPreBindProc { get; set; } // ChkPreBindProc
        public string ChkModeling { get; set; } // ChkModeling
        public string ChkUwCompliance { get; set; } // ChkUWCompliance
        
        public grs_VGrsDealsByStatu()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSNotes
    public partial class grs_VGrsNote
    {
        public int Notenum { get; set; } // notenum
        public int? Dealnum { get; set; } // dealnum
        public DateTime? Notedate { get; set; } // notedate
        public int? Notetype { get; set; } // notetype
        public string Notes { get; set; } // notes
        public int? Whoentered { get; set; } // whoentered
        public string Name { get; set; } // Name
        public string FirstName { get; set; } // FirstName
        public string MiddleName { get; set; } // MiddleName
        public string LastName { get; set; } // LastName
        public int? CreatedBy { get; set; } // CreatedBy
        
        public grs_VGrsNote()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSUserView
    public partial class grs_VGrsUserView
    {
        public int ViewId { get; set; } // view_id
        public int Userid { get; set; } // userid
        public string Screenname { get; set; } // screenname
        public string Viewname { get; set; } // viewname
        public bool @Default { get; set; } // default
        public string Layout { get; set; } // layout
        public DateTime? UserViewCreationDate { get; set; } // UserViewCreationDate
        public bool Customview { get; set; } // customview
        public int Sortorder { get; set; } // sortorder
        
        public grs_VGrsUserView()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_GRSWritingCompany
    public partial class grs_VGrsWritingCompany
    {
        public int Papernum { get; set; } // papernum
        public string Companyname { get; set; } // companyname
        public int? Cpnum { get; set; } // cpnum
        public string Relatedcompany { get; set; } // relatedcompany
        public string Address1 { get; set; } // address1
        public string Address2 { get; set; } // address2
        public string Address3 { get; set; } // address3
        public string City { get; set; } // city
        public string State { get; set; } // state
        public string Postalcode { get; set; } // postalcode
        public string Country { get; set; } // country
        public string Phone { get; set; } // phone
        public string Fax { get; set; } // fax
        public string Imagefilename { get; set; } // imagefilename
        public string CompanyShortname { get; set; } // company_shortname
        public byte? SlTrequired { get; set; } // SLTrequired
        public byte? IpTrequired { get; set; } // IPTrequired
        public string PolicynumberToken { get; set; } // policynumber_token
        public int? Currency { get; set; } // currency
        public int? Territory { get; set; } // territory
        public byte Active { get; set; } // active
        public bool HideUnusedClaimCategory { get; set; } // HideUnusedClaimCategory
        public string JeCode { get; set; } // JECode
        public int? IsGrsDisplay { get; set; } // IsGRSDisplay
        
        public grs_VGrsWritingCompany()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_KeyDocuments
    public partial class grs_VKeyDocument
    {
        public int Keydocid { get; set; } // keydocid
        public int Filenumber { get; set; } // filenumber
        public int? Producer { get; set; } // producer
        public string Docid { get; set; } // docid
        public string Docname { get; set; } // docname
        public int Sortorder { get; set; } // sortorder
        public string Location { get; set; } // location
        public string Drawer { get; set; } // drawer
        public string Folderid { get; set; } // folderid
        public string Foldername { get; set; } // foldername
        public string Doctype { get; set; } // doctype
        public string Ermsclasstype { get; set; } // ermsclasstype
        public string Filetype { get; set; } // filetype
        public string Dmspath { get; set; } // dmspath
        public int? Itemcategoryid { get; set; } // itemcategoryid
        public string Ermscategory { get; set; } // ermscategory
        public string Lastupdateduser { get; set; } // lastupdateduser
        public DateTime? Lasttimestamp { get; set; } // lasttimestamp
        public DateTime? Dmscreated { get; set; } // dmscreated
        public DateTime? Dmsupdated { get; set; } // dmsupdated
        
        public grs_VKeyDocument()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // v_PaperExt
    public partial class grs_VPaperExt
    {
        public int Papernum { get; set; } // papernum
        public string Companyname { get; set; } // companyname
        public int? Cpnum { get; set; } // cpnum
        public string Addr1 { get; set; } // addr1
        public string Addr2 { get; set; } // addr2
        public string Addr3 { get; set; } // addr3
        public string City { get; set; } // city
        public string State { get; set; } // state
        public string Postalcode { get; set; } // postalcode
        public string Cty { get; set; } // cty
        public string Phone { get; set; } // phone
        public string Fax { get; set; } // fax
        public string Imagefilename { get; set; } // imagefilename
        public string CompanyShortname { get; set; } // company_shortname
        public byte? SlTrequired { get; set; } // SLTrequired
        public byte? IpTrequired { get; set; } // IPTrequired
        public int? Territory { get; set; } // Territory
        public int? Currency { get; set; } // Currency
        public byte Active { get; set; } // active
        public DateTime CloseDate { get; set; } // CloseDate
        public DateTime RestrictDate { get; set; } // RestrictDate
        public string PaperToken { get; set; } // paper_token
        public DateTime? RptLastCloseDate { get; set; } // RptLastCloseDate
        public bool HideUnusedClaimCategory { get; set; } // HideUnusedClaimCategory
        public DateTime? ComplianceCloseDate { get; set; } // ComplianceCloseDate
        public DateTime? RptLastComplianceCloseDate { get; set; } // RptLastComplianceCloseDate
        public DateTime? OutwardCloseDate { get; set; } // OutwardCloseDate
        public DateTime? OutwardRestrictDate { get; set; } // OutwardRestrictDate
        public DateTime? RptLastOutwardCloseDate { get; set; } // RptLastOutwardCloseDate
        public string JeCode { get; set; } // JECode
        public DateTime? ClaimsCloseDate { get; set; } // ClaimsCloseDate
        public DateTime? RptLastClaimsCloseDate { get; set; } // RptLastClaimsCloseDate
        public bool RptExclude { get; set; } // RptExclude
        public string RptJe { get; set; } // RptJE
        public string CompanyPrintName { get; set; } // companyPrintName
        public int? AssumedFlag { get; set; } // AssumedFlag
        public string AssumedSortOrder { get; set; } // AssumedSortOrder
        public int? CededFlag { get; set; } // CededFlag
        public string CededSortOrder { get; set; } // CededSortOrder
        
        public grs_VPaperExt()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_catalogdef
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class TbCatalogdef
    {
        public int Catid { get; set; } // catid (Primary key)
        public string Catname { get; set; } // catname
        public int? Usecharcode { get; set; } // usecharcode
        public string Constname { get; set; } // constname
        public string Intdesc1 { get; set; } // intdesc1
        public string Strdesc1 { get; set; } // strdesc1
        public string FloatDesc1 { get; set; } // FloatDesc1

        // Reverse navigation
        public virtual ICollection<TbCatalogitem> TbCatalogitems { get; set; } // Many to many mapping
        
        public TbCatalogdef()
        {
            Usecharcode = 0;
            TbCatalogitems = new List<TbCatalogitem>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_catalogitems
    public partial class TbCatalogitem
    {
        public int Catid { get; set; } // catid (Primary key)
        public int Catorder { get; set; } // catorder
        public int Code { get; set; } // code (Primary key)
        public string Charcode { get; set; } // charcode
        public string Name { get; set; } // name
        public bool Active { get; set; } // active

        ///<summary>
        /// Associated integer data
        ///</summary>
        public int? Intdata1 { get; set; } // intdata1
        public string Strdata1 { get; set; } // strdata1
        public double? FloatData1 { get; set; } // FloatData1

        // Foreign keys
        public virtual TbCatalogdef TbCatalogdef { get; set; } // FK_tb_catalogitems_tb_catalogdef
        
        public TbCatalogitem()
        {
            Catorder = 0;
            Active = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_chklistvals
    public partial class TbChklistval
    {
        public int Entitynum { get; set; } // entitynum (Primary key)
        public int Chklistnum { get; set; } // chklistnum (Primary key)
        public int Key1 { get; set; } // key1 (Primary key)
        public int Key2 { get; set; } // key2 (Primary key)
        public int Key3 { get; set; } // key3 (Primary key)
        public string Userid { get; set; } // userid
        public DateTime? Completed { get; set; } // completed
        public int? PersonId { get; set; } // PersonId
        public string Notes { get; set; } // Notes
        
        public TbChklistval()
        {
            Key2 = -1;
            Key3 = -1;
            Completed = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_clauses
    public partial class TbClaus
    {
        public int Dealnum { get; set; } // dealnum (Primary key)
        public string Clauses { get; set; } // clauses
        public string Zzpremium { get; set; } // zzpremium
        public string Ddesc { get; set; } // ddesc
        public string Motive { get; set; } // motive
        public string Psnotes { get; set; } // psnotes
        public string Decreason { get; set; } // decreason
        public string Cover { get; set; } // cover
        public string Situation { get; set; } // situation
        public string Zzexpana { get; set; } // zzexpana
        public string Lossexp { get; set; } // lossexp
        public string Prcana { get; set; } // prcana
        public string Zzreinnotes { get; set; } // zzreinnotes
        public string UmIntroComment { get; set; } // umIntroComment
        public string UmExposureAndPricing { get; set; } // umExposureAndPricing
        public string UmLayerLoss { get; set; } // umLayerLoss
        public string UmWorstCaseScenario { get; set; } // umWorstCaseScenario
        public string UmOther { get; set; } // umOther
        public string PricingNotes { get; set; } // PricingNotes

        // Foreign keys
        public virtual TblDeal TblDeal { get; set; } // FK_tb_clauses_tbl_deals
        
        public TbClaus()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_ComGrpReq
    public partial class TbComGrpReq
    {
        public int StatusId { get; set; } // StatusId (Primary key)
        public bool Active { get; set; } // Active
        
        public TbComGrpReq()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_dealnotes
    public partial class TbDealnote
    {
        public int Notenum { get; set; } // notenum (Primary key)
        public int? Dealnum { get; set; } // dealnum
        public int? Claimnum { get; set; } // claimnum
        public DateTime? Notedate { get; set; } // notedate
        public int? Notetype { get; set; } // notetype
        public string Notes { get; set; } // notes
        public DateTime? Dateentered { get; set; } // dateentered
        public int? Whoentered { get; set; } // whoentered
        public string Whoresp { get; set; } // whoresp
        public string Type4D { get; set; } // type4d
        public int? Amount { get; set; } // amount
        public bool KeyNote { get; set; } // KeyNote
        public int? CreatedBy { get; set; } // CreatedBy

        // Foreign keys
        public virtual TblDeal TblDeal { get; set; } // FK_tb_dealnotes_tbl_deals
        
        public TbDealnote()
        {
            KeyNote = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_deal_pipeline
    public partial class TbDealPipeline
    {
        public int DealNum { get; set; } // DealNum (Primary key)
        public int? Ta { get; set; } // TA
        public int? ModelPriority { get; set; } // ModelPriority
        public int? JobSize { get; set; } // JobSize
        public string KeyLocation { get; set; } // KeyLocation
        public string DeclineReason { get; set; } // DeclineReason
        public int? ClaimsTeam { get; set; } // ClaimsTeam
        public int? IsoglClassCodeFk { get; set; } // ISOGLClassCodeFK
        public string IntegrationReferenceKey { get; set; } // IntegrationReferenceKey
        public double? TimeToCalcTotalIncurred { get; set; } // TimeToCalcTotalIncurred
        public byte? AutoCalcClaimIncurred { get; set; } // AutoCalcClaimIncurred
        public byte? AutoRefreshClaimLimitDed { get; set; } // AutoRefreshClaimLimitDed
        public byte? ReviewClaimLimits { get; set; } // ReviewClaimLimits
        public DateTime? QuotedDate { get; set; } // QuotedDate

        // Foreign keys
        public virtual TblDeal TblDeal { get; set; } // FK_deal_pipeline
        
        public TbDealPipeline()
        {
            AutoCalcClaimIncurred = 1;
            AutoRefreshClaimLimitDed = 0;
            ReviewClaimLimits = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_DocChkValue
    public partial class TbDocChkValue
    {
        public int ValueId { get; set; } // Value_Id (Primary key)
        public int ItemId { get; set; } // Item_Id
        public int Key1 { get; set; } // Key1
        public int? Key2 { get; set; } // Key2
        public int? Key3 { get; set; } // Key3
        public string Reference { get; set; } // Reference
        public byte? FileFlag { get; set; } // File_Flag
        public byte? DmsFlag { get; set; } // DMS_Flag
        public string DmsDocId { get; set; } // DMS_DocId
        public byte? NaFlag { get; set; } // NA_Flag
        public string LastUser { get; set; } // Last_User
        public DateTime? LastTimestamp { get; set; } // Last_Timestamp
        public string Notes { get; set; } // Notes
        public string DmsDocName { get; set; } // DMS_DocName
        public bool? DmsIsValid { get; set; } // DMS_IsValid
        public DateTime? DmsCreated { get; set; } // DMS_Created
        public DateTime? DmsUpdated { get; set; } // DMS_Updated
        public string DmsFileType { get; set; } // DMS_FileType
        public string DmsDocType { get; set; } // DMS_DocType
        
        public TbDocChkValue()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tbl_deals
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class TblDeal
    {
        public int Dealnum { get; set; } // dealnum (Primary key)
        public string Revnum { get; set; } // revnum
        public string Dealname { get; set; } // dealname
        public int? Cpartynum { get; set; } // cpartynum
        public int? Capmgr { get; set; } // capmgr
        public int? Busunit { get; set; } // busunit
        public int? Cgrp { get; set; } // cgrp
        public int? Liabtype { get; set; } // liabtype
        public int? Exposuretype { get; set; } // exposuretype
        public int? Underwriter { get; set; } // underwriter
        public int? Currency { get; set; } // currency
        public int? Source { get; set; } // source
        public int? Rsource { get; set; } // rsource
        public int? Bbroker { get; set; } // bbroker
        public int? Rbroker { get; set; } // rbroker
        public int? Zzhavedata { get; set; } // zzhavedata
        public int? Prob { get; set; } // prob
        public decimal? Estsize { get; set; } // estsize
        public string Genericname { get; set; } // genericname
        public int? Status { get; set; } // status
        public string Statusaction { get; set; } // statusaction
        public DateTime? Datecreated { get; set; } // datecreated
        public DateTime? Lastupdtdt { get; set; } // lastupdtdt
        public DateTime? Submissiondate { get; set; } // submissiondate
        public DateTime? Targetdt { get; set; } // targetdt
        public int? Yearbound { get; set; } // yearbound
        public int? Contractnum { get; set; } // contractnum
        public int? Pcdealnum { get; set; } // pcdealnum
        public DateTime? Inceptdate { get; set; } // inceptdate
        public DateTime? Binddate { get; set; } // binddate
        public DateTime? Riskdate { get; set; } // riskdate
        public DateTime? Cfdate { get; set; } // cfdate
        public DateTime? Expirydate { get; set; } // expirydate
        public string Dealcomment { get; set; } // dealcomment
        public DateTime? Termdate { get; set; } // termdate
        public int? Termreason { get; set; } // termreason
        public int? Retrospective { get; set; } // retrospective
        public int? Deposit { get; set; } // deposit
        public int? Riskcatagory { get; set; } // riskcatagory
        public int? Riskband { get; set; } // riskband
        public int? Busclass { get; set; } // busclass
        public int? Reinsurance { get; set; } // reinsurance
        public int? Policybasis { get; set; } // policybasis
        public int? Resvcatagory { get; set; } // resvcatagory
        public int? Renewal { get; set; } // renewal
        public int? Covtype { get; set; } // covtype
        public int? Prembasis { get; set; } // prembasis
        public int? Territory { get; set; } // territory
        public int? Fwh { get; set; } // fwh
        public int? Premdelay { get; set; } // premdelay
        public int? Reportdelay { get; set; } // reportdelay
        public int? Premtype { get; set; } // premtype
        public int? Lossstatus { get; set; } // lossstatus
        public int? Producer { get; set; } // producer
        public int? Uw1 { get; set; } // uw1
        public int? Uw2 { get; set; } // uw2
        public int? Act1 { get; set; } // act1
        public int? Act2 { get; set; } // act2
        public int? Peer { get; set; } // peer
        public int? Legal1 { get; set; } // legal1
        public int? Legal2 { get; set; } // legal2
        public int? Accting { get; set; } // accting
        public int? Riskmgmt { get; set; } // riskmgmt
        public int? Inclxpl { get; set; } // inclxpl
        public int? Incleco { get; set; } // incleco
        public int? Inclbio { get; set; } // inclbio
        public int? Inclnuc { get; set; } // inclnuc
        public int? Inclchem { get; set; } // inclchem
        public string Sunset { get; set; } // sunset
        public string Sunrise { get; set; } // sunrise
        public string Fileref { get; set; } // fileref
        public int? Mprognum { get; set; } // mprognum
        public string Outlook { get; set; } // outlook
        public string Netdir { get; set; } // netdir
        public int? Glbusunit { get; set; } // glbusunit
        public int? Glcovtype { get; set; } // glcovtype
        public int? Glbustype { get; set; } // glbustype
        public int? Glcty { get; set; } // glcty
        public int? Glyrwritten { get; set; } // glyrwritten
        public int? Geoseg { get; set; } // geoseg
        public int? Outward { get; set; } // outward
        public string Claimsdir { get; set; } // claimsdir
        public int? Paper { get; set; } // paper
        public int? Retrochked { get; set; } // retrochked
        public int? Dealtype { get; set; } // dealtype
        public string Policynum { get; set; } // policynum
        public int? Paydelay { get; set; } // paydelay
        public int Interco { get; set; } // interco
        public bool? IsAgg { get; set; } // IsAgg
        public int? ParentDeal { get; set; } // ParentDeal
        public int? PlanGrp { get; set; } // PlanGrp
        public bool? Continuous { get; set; } // continuous
        public int? Sourcelocation { get; set; } // sourcelocation
        public int? Rsourcelocation { get; set; } // rsourcelocation
        public int? Cpartylocation { get; set; } // cpartylocation
        public int? CalcExpType { get; set; } // CalcExpType
        public int? Mga { get; set; } // mga
        public int? Captivelocation { get; set; } // captivelocation
        public int? Region { get; set; } // Region
        public bool? ExpiryEod { get; set; } // Expiry_EOD
        public DateTime? QuoteByDate { get; set; } // QuoteByDate
        public int? ApprovalType { get; set; } // ApprovalType
        public int? Modeller { get; set; } // Modeller
        public bool? ReviewByUw { get; set; } // ReviewByUW
        public byte? Jecategory { get; set; } // jecategory
        public int IntegrationSource { get; set; } // IntegrationSource
        public int? AgreementId { get; set; } // AgreementId
        public bool? Downgraded { get; set; } // downgraded
        public int? Compliant { get; set; } // compliant
        public string Homestate { get; set; } // homestate
        public DateTime? NonrenewMaildt { get; set; } // nonrenew_maildt
        public DateTime? NoticecancMaildt { get; set; } // noticecanc_maildt
        public DateTime? NoticecancDuedt { get; set; } // noticecanc_duedt
        public bool? PmtReceived { get; set; } // pmt_received
        public bool? PriorHistory { get; set; } // prior_history
        public int? Risklocation { get; set; } // risklocation
        public int? BrokerTypeId { get; set; } // BrokerTypeId
        public int? BrokerTypeId2 { get; set; } // BrokerTypeId2
        public int? ProjectIndicator { get; set; } // ProjectIndicator
        public string SlTransactionNumber { get; set; } // SLTransactionNumber
        public bool? DeRegulated { get; set; } // DeRegulated
        public int? UAssistant { get; set; } // UAssistant
        public decimal? TivAmount { get; set; } // TIVAmount
        public int? OccupancyNum { get; set; } // OccupancyNum
        public int? BusClassCode { get; set; } // BusClassCode
        public string SubmissionScore { get; set; } // SubmissionScore
        public string BindAmsCode { get; set; } // BindAMSCode
        public int? BindAmsRegionCode { get; set; } // BindAMSRegionCode
        public string NaicsCode { get; set; } // NAICSCode
        public string RiskComplexityType { get; set; } // RiskComplexityType
        public bool? IsManualBreakdown { get; set; } // IsManualBreakdown

        // Reverse navigation
        public virtual ICollection<TbDealnote> TbDealnotes { get; set; } // tb_dealnotes.FK_tb_dealnotes_tbl_deals
        public virtual ICollection<TblDeal> TblDeals { get; set; } // tbl_deals.FK_tbl_deals_parent
        public virtual TbClaus TbClaus { get; set; } // tb_clauses.FK_tb_clauses_tbl_deals
        public virtual TbDealPipeline TbDealPipeline { get; set; } // tb_deal_pipeline.FK_deal_pipeline

        // Foreign keys
        public virtual TblDeal TblDeal_ParentDeal { get; set; } // FK_tbl_deals_parent
        
        public TblDeal()
        {
            Revnum = "2003";
            Outward = 0;
            Paper = 1;
            Retrochked = 0;
            Interco = 0;
            IsAgg = false;
            PlanGrp = 0;
            IntegrationSource = 0;
            OccupancyNum = 0;
            IsManualBreakdown = false;
            TbDealnotes = new List<TbDealnote>();
            TblDeals = new List<TblDeal>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_Person
    public partial class TbPerson
    {
        public int PersonId { get; set; } // PersonId
        public int? LocationId { get; set; } // LocationId
        public int? Nationality { get; set; } // Nationality
        public string LastName { get; set; } // LastName
        public string FirstName { get; set; } // FirstName
        public string MiddleName { get; set; } // MiddleName
        public string Prefix { get; set; } // Prefix
        public string Suffix { get; set; } // Suffix
        public string Ssn { get; set; } // SSN
        public DateTime? AppointDate { get; set; } // AppointDate
        public DateTime? ResignDate { get; set; } // ResignDate
        public string JobTitle { get; set; } // JobTitle
        public string Department { get; set; } // Department
        public string PersonAddress { get; set; } // PersonAddress
        public string PersonCity { get; set; } // PersonCity
        public string PersonState { get; set; } // PersonState
        public string PersonPostCode { get; set; } // PersonPostCode
        public int? PersonCountryId { get; set; } // PersonCountryId
        public string ManagerName { get; set; } // ManagerName
        public int? ManagerId { get; set; } // ManagerId
        public string AssistantName { get; set; } // AssistantName
        public int? AssistantId { get; set; } // AssistantId
        public string PersonNotes { get; set; } // PersonNotes
        public string PersonAddress2 { get; set; } // PersonAddress2
        public string PersonCity2 { get; set; } // PersonCity2
        public string PersonState2 { get; set; } // PersonState2
        public string PersonPostCode2 { get; set; } // PersonPostCode2
        public int? PersonCountryId2 { get; set; } // PersonCountryId2
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime? CreatedOn { get; set; } // CreatedOn
        public string UpdatedBy { get; set; } // UpdatedBy
        public DateTime? UpdatedOn { get; set; } // UpdatedOn
        public string PersonName { get; set; } // PersonName
        public bool? Deleted { get; set; } // Deleted
        public string Biography { get; set; } // Biography
        public string CommonName { get; set; } // CommonName
        public string FunctionalTitle { get; set; } // FunctionalTitle
        public int PersonSid { get; set; } // PersonSID
        public int? CompanyId { get; set; } // CompanyId
        public Guid? AmsContactGuid { get; set; } // AMSContactGUID
        public int? PersonStatus { get; set; } // PersonStatus
        
        public TbPerson()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // tb_user
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class TbUser
    {
        public int Userid { get; set; } // userid (Primary key)
        public string Lastname { get; set; } // lastname
        public string Firstname { get; set; } // firstname
        public string Middlename { get; set; } // middlename
        public string Businessphone { get; set; } // businessphone
        public string Faxphone { get; set; } // faxphone
        public string Loginid { get; set; } // loginid
        public string Emailid { get; set; } // emailid
        public string Passwordtx { get; set; } // passwordtx
        public DateTime? Loginexpdt { get; set; } // loginexpdt
        public int? ContactNum { get; set; } // ContactNum
        public string AlternativeLoginId { get; set; } // AlternativeLoginID
        public Guid? Guid { get; set; } // GUID
        public string Pguid { get; set; } // PGUID
        public byte IsEnabled { get; set; } // IsEnabled
        public string ReportId { get; set; } // ReportID
        public string Sid { get; set; } // SID
        public string DistinguishedName { get; set; } // DistinguishedName

        // Reverse navigation
        public virtual ICollection<grs_TblUserview> grs_TblUserviews { get; set; } // tbl_userviews.FK_tb_user_tbl_userviews
        
        public TbUser()
        {
            IsEnabled = 1;
            grs_TblUserviews = new List<grs_TblUserview>();
            InitializePartial();
        }

        partial void InitializePartial();
    }


    // ************************************************************************
    // Stored procedure return models

    public partial class grs_PrGetGrsDealCountByStatus
    {
        public Int32 StatusGroup { get; set; }
        public String StatusGroupName { get; set; }
        public Int32 StatusCode { get; set; }
        public String StatusName { get; set; }
        public Int32 StatusGroupSortOrder { get; set; }
        public Int32 StatusSortOrder { get; set; }
        public Int32 WorkflowID { get; set; }
        public String WorkflowName { get; set; }
        public Int32? Count { get; set; }
    }

    public partial class grs_PrLckGetLockedItem
    {
        public Int32 LockID { get; set; }
        public Int32 CategoryID { get; set; }
        public Int32 ItemID { get; set; }
        public Int32 UserID { get; set; }
        public Int32 SessionID { get; set; }
        public String DataBaseName { get; set; }
        public Boolean IsEditLock { get; set; }
        public String Notes { get; set; }
        public DateTime EntryTime { get; set; }
        public DateTime ExpirationTime { get; set; }
        public String LockingUser { get; set; }
        public String LockingUserName { get; set; }
    }

}
// </auto-generated>


