#%RAML 1.0 ResourceType
##### COLLECTION #####
usage: Use this to describe resource that list items

get:
  description: "Get a list of <<item>>s based on criteria (Search)"
  responses:
    200: # OK
      body:
        application/json:
          type: object
          properties:
            url: string
            totalRecords?: integer
            offset?: integer
            limit?: integer
            results:
              description: "Collection of <<item>>s and Links"
              type: array
              items:
                type: object
                properties:
                  data: <<item>>
                  links?: !include ../types/links.raml
            messages?:
              type: array
              items: !include ../types/responseMessage.raml
          #example: <<getResponse_singleExample>>
          examples:
            single_example: <<getResponse_singleExample>>
            array_example: <<getResponse_arrayExample>>
