#%RAML 1.0 ResourceType
##### MEMBER #####
get:
  description: Get a <<item>>
  responses:
    200: # OK
      body:
        application/json:
          description: "<<item>> and Links"
          type: object
          properties:
            url: string
            data: <<item>>
            links?: !include ../types/links.raml
            messages?:
              type: array
              items: !include ../types/responseMessage.raml
          example: <<getResponse_example>>

    404: # Not Found
      body:
        application/json:
          example: |
            { "message": "<<item>> not found" }

put:
  description: Save (update) an existing <<put_item>>
  body:
    application/json:
      type: <<put_item>>
      example: <<put_example>>

  responses:
    200: # OK
      body:
        application/json:
          description: "Updated <<item>> and Links"
          type: object
          properties:
            url: string
            data: <<item>>
            links?: !include ../types/links.raml
            messages?:
              type: array
              items: !include ../types/responseMessage.raml
          example: <<getResponse_example>>
    400:
      body:
        application/json:
          description: |
            The request could not be understood by the server due to malformed syntax.
            The client SHOULD NOT repeat the request without modifications.
          type: object
          properties:
            url: string
            errors:
              type: array
              items: !include ../types/responseMessage.raml
          example: <<putResponse400_example>>
