// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class Cedant
    {
        [Required]
        [JsonProperty("cedantid")]
        public int? Cedantid { get; set; } // cedantid
        [JsonProperty("cedantname")]
        public string Name { get; set; } // cedant
        //[JsonProperty("")]
        //public int? Parentgrouptypeid { get; set; } // parentgrouptypeid
        //[JsonProperty("")]
        //public string Parentgrouptype { get; set; } // parentgrouptype
        [JsonProperty("locationid")]
        public int Locationid { get; set; } // locationid
        //[JsonProperty("")]
        //public string Locationname { get; set; } // locationname
        [JsonProperty("address")]
        public string Locationaddress { get; set; } // locationaddress
        [JsonProperty("city")]
        public string Locationcity { get; set; } // locationcity
        [JsonProperty("state")]
        public string Locationstate { get; set; } // locationstate
        [JsonProperty("postalcode")]
        public string Locationpostcode { get; set; } // locationpostcode
        [JsonProperty("country")]
        public string Country { get; set; } // country
        //[JsonProperty("")]
        //public string Parentcompanyname { get; set; } // parentcompanyname
        //[JsonProperty("")]
        //public string Cedantcategories { get; set; } // cedantcategories
        //[JsonProperty("")]
        //public string Cedantcategoryid { get; set; } // cedantcategoryid
        [JsonProperty("parentgroupid")]
        public int? Cedantgroupid { get; set; } // Cedantgroupid
        [JsonProperty("parentgroupname")]
        public string Cedantgroupname { get; set; } // Cedantgroupname
    }
}