// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class DealDocuments
    {
        [JsonProperty("KeyDocid")]
        public int KeyDocid { get; set; } // keydocid (Primary key)
        [JsonProperty("FileNumber")]
        public int? FileNumber { get; set; } // filenumber
        [JsonProperty("Producer")]
        public int? Producer { get; set; } // producer
        [JsonProperty("Docid")]
        public string Docid { get; set; } // docid
        [JsonProperty("DocName")]
        public string DocName { get; set; } // docname
        [JsonProperty("SortOrder")]
        public int SortOrder { get; set; } // sortorder
        [JsonProperty("Location")]
        public string Location { get; set; } // location
        [JsonProperty("Drawer")]
        public string Drawer { get; set; } // drawer
        [JsonProperty("Folderid")]
        public string Folderid { get; set; } // folderid
        [Required]
        [JsonProperty("FolderName")]
        public string FolderName { get; set; } // foldername
        [Required]
        [JsonProperty("DocType")]
        public string DocType { get; set; } // doctype
        [JsonProperty("ErmsClassType")]
        public string ErmsClassType { get; set; } // ermsclasstype
        [JsonProperty("FileType")]
        public string FileType { get; set; } // filetype
        [JsonProperty("DmsPath")]
        public string DmsPath { get; set; } // dmspath
        [JsonProperty("ItemCategoryid")]
        public int? ItemCategoryid { get; set; } // itemcategoryid
        [JsonProperty("ErmsCategory")]
        public string ErmsCategory { get; set; } // ermscategory
        [JsonProperty("LastUpdatedUser")]
        public string LastUpdatedUser { get; set; } // lastupdateduser
        [JsonProperty("LastTimeStamp")]
        public DateTime? LastTimeStamp { get; set; } // lasttimestamp
        [JsonProperty("DmsCreated")]
        public DateTime? DmsCreated { get; set; } // dmscreated
        [JsonProperty("DmsUpdated")]
        public DateTime? DmsUpdated { get; set; } // dmsupdated
    }
}