// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class Deal
    {
        

        [Required]
		[JsonProperty("dealNumber")]
        public int DealNumber { get; set; }

        [MaxLength(100)]
		[JsonProperty("dealName")]
        public string DealName { get; set; }


		[JsonProperty("statusCode")]
        public int? StatusCode { get; set; }

        [MaxLength(100)]
		[JsonProperty("status")]
        public string Status { get; set; }


		[JsonProperty("contractNumber")]
        public int? ContractNumber { get; set; }


		[JsonProperty("inceptionDate")]
        public string InceptionDate { get; set; }


		[JsonProperty("targetDate")]
        public string TargetDate { get; set; }


		[JsonProperty("priority")]
        public int? Priority { get; set; }


		[JsonProperty("submittedDate")]
        public string SubmittedDate { get; set; }


		[JsonProperty("primaryUnderwriterCode")]
        public int? PrimaryUnderwriterCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("primaryUnderwriterName")]
        public string PrimaryUnderwriterName { get; set; }


		[JsonProperty("secondaryUnderwriterCode")]
        public int? SecondaryUnderwriterCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("secondaryUnderwriterName")]
        public string SecondaryUnderwriterName { get; set; }


		[JsonProperty("technicalAssistantCode")]
        public int? TechnicalAssistantCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("technicalAssistantName")]
        public string TechnicalAssistantName { get; set; }


		[JsonProperty("modellerCode")]
        public int? ModellerCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("modellerName")]
        public string ModellerName { get; set; }


		[JsonProperty("actuaryCode")]
        public int? ActuaryCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("actuaryName")]
        public string ActuaryName { get; set; }


		[JsonProperty("expiryDate")]
        public string ExpiryDate { get; set; }


		[JsonProperty("brokerCode")]
        public int? BrokerCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("brokerName")]
        public string BrokerName { get; set; }


		[JsonProperty("brokerContactCode")]
        public int? BrokerContactCode { get; set; }

        [MaxLength(200)]
		[JsonProperty("brokerContactName")]
        public string BrokerContactName { get; set; }

        [JsonProperty("brokerGroupCode")]
        public int? BrokerGroupCode { get; set; }

        [MaxLength(200)]
        [JsonProperty("brokerGroupName")]
        public string BrokerGroupName { get; set; }

		[JsonProperty("cedantCode")]
		public int? CedantCode { get; set; }

		[MaxLength(200)]
		[JsonProperty("cedantName")]
		public string CedantName { get; set; }

        [JsonProperty("cedantGroupCode")]
        public int? CedantGroupCode { get; set; }

        [MaxLength(200)]
        [JsonProperty("cedantGroupName")]
        public string CedantGroupName { get; set; }

		[JsonProperty("continuous")]
		public bool? Continuous { get; set; }

        [JsonProperty("cedantLocationCode")]
        public int? CedentLocation { get; set; }
        
        [JsonProperty("cedantLocationName")]
        public string CedentLocationname { get; set; }

        [JsonProperty("brokerLocationCode")]
        public int? BrokerLocation { get; set; }

        [JsonProperty("brokerLocationName")]
        public string BrokerLocationname { get; set; }

        [JsonProperty("paper")]
        public string PaperName { get; set; }

        [JsonProperty("renewal")]
        public int? Renewal { get; set; }

        [JsonProperty("renewalName")]
        public string RenewalName { get; set; }

        [JsonProperty("expiresAtEndOfDate")]
        public bool? ExpiryEod { get; set; }

        [JsonProperty("exposureTypeCode")]
        public int? Exposuretype { get; set; }

        [JsonProperty("dealTypeCode")]
        public int? Dealtype { get; set; }

        [JsonProperty("dealTypeName")]
        public string DealtypeName { get; set; }

        [JsonProperty("coverageType")]
        public int? Coveragetype { get; set; }

        [JsonProperty("coverageName")]
        public string CoveragetypeName { get; set; }

        [JsonProperty("policyBasis")]
        public int? Policybasis { get; set; }

        [JsonProperty("policyBasisName")]
        public string PolicybasisName { get; set; }

        [JsonProperty("currencyCode")]
        public int? Currency { get; set; }

        [JsonProperty("currencyName")]
        public string CurrencyName { get; set; }

        [JsonProperty("domicileCode")]
        public int? Domicile { get; set; }

        [JsonProperty("domicileName")]
        public string DomicileName { get; set; }
        
        [JsonProperty("regionCode")]
        public int? Region { get; set; }

        [JsonProperty("regionName")]
        public string RegionName { get; set; }

        [JsonProperty("chkPreBindProcessing")]
        public string ChkPreBindProcessing { get; set; }

        [JsonProperty("chkUWCompliance")]
        public string ChkUWCompliance { get; set; }

        [JsonProperty("chkModeling")]
        public string ChkModelling { get; set; }

        //Add for GRS-708
        [JsonProperty("ReasonForDecline")]
        public string decreason { get; set; }

    } // end class

} // end Models namespace

