// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class PersonProfile
    {
		[JsonProperty("defaultSubdivisions")]
        public IList<int> DefaultSubDivisions { get; set; }
    } // end class

} // end Models namespace

