// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class Person
    {
        

        [Required]
		[JsonProperty("personId")]
        public int PersonId { get; set; }

        [MaxLength(100)]
		[JsonProperty("firstName")]
        public string FirstName { get; set; }

        [MaxLength(100)]
		[JsonProperty("lastName")]
        public string LastName { get; set; }

        [MaxLength(100)]
		[JsonProperty("displayName")]
        public string DisplayName { get; set; }
    } // end class

} // end Models namespace

