// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class TDealStatusSummary
    {
        


		[JsonProperty("statusCode")]
        public int? StatusCode { get; set; }

        [Required]
		[JsonProperty("statusName")]
        public string StatusName { get; set; }

        [Required]
		[JsonProperty("sortOrder")]
        public int SortOrder { get; set; }

        [Required]
		[JsonProperty("count")]
        public int Count { get; set; }


		[JsonProperty("workflowId")]
        public int? WorkflowId { get; set; }


		[JsonProperty("workflowName")]
        public string WorkflowName { get; set; }


		[JsonProperty("statusSummary")]
        public IList<TDealStatusSummary> StatusSummary { get; set; }
    } // end class

} // end Models namespace

