// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Markel.GlobalRe.Service.Underwriting.API.v1.Models
{
    public partial class TSubdivision
    {
        

        [Required]
		[JsonProperty("id")]
        public int Id { get; set; }

        [Required]
		[JsonProperty("name")]
        public string Name { get; set; }

        [Required]
		[JsonProperty("sortOrder")]
        public int SortOrder { get; set; }


		[JsonProperty("subdivisions")]
        public IList<TSubdivision> Subdivisions { get; set; }
    } // end class

} // end Models namespace

