#%RAML 1.0 DataType
##### Contract Type #####
displayName: ContractType
description: Contract Type
type: object

properties:
  Level1ExposureTypeCode:  integer
  Level1ExposureTypeValue: string
  Level1ContractTypeCode:  integer
  Level1ContractTypeValue: string
  AssumedCededAllFlag: string
