#%RAML 1.0 DataType
##### Deal Note #####
displayName: DealNote
description: Deal Note
type: object

properties:
  notenum:  integer
  dealNumber: integer
  notedate:  string
  notetype: integer
  notes: string
  whoentered: integer
